project_id = "lpmwqwpzdhtkrzoounec"

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.newsletter-subscribe]
verify_jwt = false

[functions.calculate-designer-score]
verify_jwt = true

[functions.purchase-foundation-rank]
verify_jwt = false

[functions.submit-stylebox-entry]
verify_jwt = true
